# Generated by Django 4.2.5 on 2023-09-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
