# Generated by Django 4.2.5 on 2023-09-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_studentmodel_delete_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
