# Generated by Django 4.2.5 on 2023-09-21 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_disciplinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('data_entrega', models.DateField()),
                ('concluida', models.BooleanField()),
                ('disciplines', models.ManyToManyField(related_name='Task_Disciplines', to='tasks.disciplinemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.studentmodel')),
            ],
        ),
    ]
